### ISSUE TITLE
Clicking on fields in red/blue conflict review table produces new behavior that slows down review process

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#156] opened 2016-01-08 19:23 UTC
I think in the refactoring of Conflict.js we've added some extra latency for going through reviews.  This is one of the examples where when you click on the fields it triggers the pop-up message, "Please wait while panning to next review...".  In some cases this can delay action for 5 seconds. I think this call is unnecessary and should be removed because it will add substantial time when reviewing conflicts in the 100s to 1000s. The other interesting aspect of this particular review is that there is no blue POI, just the red.  Datasets are the Brazil_SaoPaulo OSM/Geonames.  Red Poi  shown in the gif is Wtc_Hotel in the geonames dataset.

 I'll open other tickets regarding any reduction in speed associated with the refactored review process.  
![panning_to_next_review](https://cloud.githubusercontent.com/assets/7560096/12207123/b587269c-b5f9-11e5-9811-79ca1e601c6f.gif)

**Comment by mjeffe98** [comment] 2016-01-08 19:29
Issue is problematic because users are accustomed to clicking on the table to select the feature to look at tags, etc.  Can't have this extra downtime for each table select.

**Comment by jchoi1267** [comment] 2016-01-08 19:51
This may not be caused by the new code but showing masking accentuated the process. Still we will need to look into optimizing the code to speed things up if possible...

**Comment by mjeffe98** [comment] 2016-01-08 21:48
For now sounds like we should disable masking when selecting items from the review table.

**Comment by jchoi1267** [comment] 2016-01-11 15:44
After looking into this, cause for this bug may be a simpler reason. We may not turning off screen lock so it is defaulting to timer which is there to ensure screen is not locked up forever... Fix might be just implementing unlock for table column click..

**Comment by jchoi1267** [comment] 2016-01-11 16:02
Committed to release branch

**Comment by mjeffe98** [comment] 2016-01-11 23:32
Still getting significant delays after running Build.sh for release.  @jchoi1267 could you also commit to develop so I can test or do you want to constrain this fix to release?  I just want to make sure the commit made it in as I didn't see the change after rebuilding.

**Closed** 2016-01-12 17:36 UTC
Labels: Category: UI, Identified During Regression Test, Priority: High, Status: Ready for Test
