### ISSUE TITLE
Source field is overwritten 

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#146] opened 2016-01-04 14:25 UTC
On an attribution copy or conflation, the source field is overwritten, not appended to current.

**Comment by mjeffe98** [comment] 2016-01-06 19:41
@mattjdnv investigate the spec for how they handle source fields during export.

**Comment by brianhatchl** [comment] 2016-01-07 23:02
I am seeing this on Paste Tags, but that is because we have it set to overwrite.  It is trivial to change this to append, but that may cause issues with tags that have multiple values when translating to output schemas like TDS and MGCP.

I was not able to reproduce this behavior when conflating datasets.  I had two features, each with a unique 'source' tag that were matched and merged during conflation and both source values were in the output (semicolon delimited).

**Comment by mjeffe98** [comment] 2016-01-07 23:05
source tags tend to be small so it's hard to exceed a 20char limit if one does happen to exist in the output spec.  Did you have any issues exporting as fgdb file in either TDS 6.1 or MGCP?

**Comment by mjeffe98** [comment] 2016-01-07 23:11
follow-on question, @mattjdnv @brianhatchl since we are already support merging separate source tags during conflation, it seems like we should also support this using copy/paste as we are already making that assumption when conflating the features.

**Comment by brianhatchl** [comment] 2016-01-07 23:13
I didn't mean that issues would be caused by field size, but that if paste tags appends to a key that is translated, the translation will fail.  For example, 
`highway=primary` gets translated to `RIN_ROI=3` & `RTY=3` in TDS.  But if the appended value is `highway=primary;road` then I assume the translation would fail.

**Comment by brianhatchl** [comment] 2016-01-07 23:15
The bigger point is that appending tag values might create an inconsistent/contradictory state for the feature.

**Comment by brianhatchl** [comment] 2016-01-07 23:54
@jasonsurratt is it possible that hoot core has a more sophisticated merge operation that can be exposed through a nodejs service.  One that varies overwrite, append, and writing to alt_tag as appropriate for the tags in question?

**Comment by jasonsurratt** [comment] 2016-01-11 17:39
What is `alt_tag`?

There are three tag merging implementations:

* hoot::AverageTagMerger - Uses the schema to average enumerated tag types (e.g. highway=primary + highway=tertiary => highway=secondary)
* hoot::GeneralizeTagMerger - Uses the common ancestor of two tags (e.g. surface=brick + surface=asphalt => surface=paved)
* hoot::OverwriteTag2Merger - Overwrites the enumerated tags in input 2 with the tags in input 1
* hoot::OverwriteTag1Merger - Overwrites the enumerated tags in input 1 with the tags in input 2

The following rules apply to Average, Generalize and Overwrite:

If the field is a name field then there is special business logic used to keep all names in an appropriate fashion (e.g. name=foo + name=bar alt_name=baz => name=foo alt_name=bar;baz)

If the field is a unstructured text field (e.g. source, note, license, etc.) then the values will be concatenated. E.g. (source=dc + source=tiger => source=dc;tiger)

If a tag is unrecognized (e.g. not in conf/schema/*) then it is treated as an unstructured text field.

```
var HOOT_HOME = process.env.HOOT_HOME                                           
var hoot = require(HOOT_HOME + '/lib/HootJs');                                  

// I just realized this requires constructing tags objects instead of dicts. Just did this to simplify: https://github.com/ngageoint/hootenanny/issues/211
var t1 = new hoot.Tags();                                                       
t1.set("name", "foo");                                                          
t1.set("highway", "primary");                                                   
t1.set("source", "dc");                                                         
                                                                                
var t2 = new hoot.Tags();                                                       
t2.set("name", "bar");                                                          
t2.set("highway", "tertiary");                                                  
t2.set("source", "tiger");                                                      

// This is only accessible from node.js as a global setting right now, but can easily be exposed per 
// instance if needed. If you change this globally then it will also impact node.js calls to conflate, etc. 
// from a single process.
hoot.Settings.set({"tag.merger.default": "hoot::AverageTagMerger"});
hoot.log(hoot.TagMergerFactory.mergeTags(t1, t2).toDict());                     
```

Output:

```
$ nodejs tmp/example.js
10:28:03.769 INFO  ...oot-release-4/hoot/tmp/dum.js"(  15) {"alt_name":"bar","source":"dc;tiger","name":"foo","highway":"secondary"}
```

**Comment by brianhatchl** [comment] 2016-01-11 18:11
alt_tag refers to the logic mentioned here,
> If the field is a name field then there is special business logic used to keep all names in an appropriate > fashion (e.g. name=foo + name=bar alt_name=baz => name=foo alt_name=bar;baz)

**Comment by jasonsurratt** [comment] 2016-01-11 18:17
The name handling applies to a lot of "name-ish" fields, but names are special. E.g `loc_name`, `official_name`, foreign language fields `name:*`, etc. But they all get handled in much the same way. If there are duplicate name fields with different values then I append the extra values into `alt_name`. If there are duplicates then I'll drop the duplicates.

I can't think of other fields right now that get similar handling.

**Comment by brianhatchl** [comment] 2016-01-14 16:18
After the TEM, it was decided to keep the logic in the browser, and support both append and overwrite paste operations, https://github.com/ngageoint/hootenanny-ui/issues/172.

**Comment by mjeffe98** [comment] 2016-01-18 21:29
Closed with https://github.com/ngageoint/hootenanny-ui/issues/172.  User has the option to append or overwrite the source tag depending which short-key combo they use.

**Closed by mjeffe98** 2016-01-18 21:29 UTC
Labels: Category: UI, Priority: High, Status: New/Undefined, Type: Task
