### ISSUE TITLE
Add area merging to the UI

### ISSUE THREAD

**Issue by bwitham** [ngageoint/hootenanny-ui#767] opened 2016-10-06 17:40 UTC
A merge button should be shown for area to area reviews like it is shown for POI to POI reviews.  The merge arrow by default should point from secondary feature to reference feature and can be reversed.  Add a unit test.

**Comment by brianhatchl** [comment] 2020-07-30 14:18
duplicate of #1003

**Closed by brianhatchl** 2020-07-30 14:18 UTC
Labels: Category: UI, Defined, Priority: Medium, Type: Feature
