### ISSUE TITLE
Right-click dataset context menu is selecting datasets

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-ui#51] opened 2015-12-02 17:24 UTC
This leads to datasets being unselected if multiple are selected and Ctrl is not held down. Or "visually" deselecting the dataset under the right mouse click if Ctrl is held down.

The click handler for the dataset rows should ignore right-clicks.

**Comment by sisskind** [comment] 2015-12-02 17:28
@brianhatchl will ignore right click if control is held down, but doesn't it make sense to allow user to right click to select one dataset and open context menu?

**Comment by brianhatchl** [comment] 2015-12-02 17:40
I've always left-clicked to select dataset, then right-click to open context menu.  Not sure if single right-click to select and open is commonly used by most people.

**Comment by brianhatchl** [comment] 2015-12-02 17:40
It leads to some confusing behavior when multiple datasets and Ctrl-click selected.

**Comment by sisskind** [comment] 2015-12-02 17:40
No problem -- makes more sense to stay consistent.  Updating now.

**Comment by sisskind** [comment] 2015-12-02 17:47
Brian -- can you review/merge?

https://github.com/ngageoint/hootenanny-ui/compare/develop...issue-51

**Comment by brianhatchl** [comment] 2015-12-02 17:54
I like that behavior much better, but minor gripe, should left-clicking a selected row deselect it?

**Comment by sisskind** [comment] 2015-12-02 17:58
Don't think so - because you could have selected multiples and then left-click to open context menu.  When I've tested, looks like it is not deselected. Are you seeing different behavior?

**Comment by brianhatchl** [comment] 2015-12-02 18:18
Was trying to say a left-click should deselect a selected row.  Currently it does not.

**Comment by sisskind** [comment] 2015-12-02 18:19
But if you left-click a selected row to open context menu, it would be de-selected, right?

**Comment by brianhatchl** [comment] 2015-12-02 18:21
context menu = right-click ;-)

**Comment by sisskind** [comment] 2015-12-02 18:22
Need emoticon for brain fart.  Looking into.

**Comment by sisskind** [comment] 2015-12-02 18:32
@brianhatchl fixed - ready for review/merge (https://github.com/ngageoint/hootenanny-ui/compare/develop...issue-51)

**Comment by mjeffe98** [comment] 2015-12-02 20:04
will this make it into 0.2.19 release that @mv003348 is working on?

**Comment by sisskind** [comment] 2015-12-02 20:12
I believe @mv003348 said we have until tonight.

**Comment by sisskind** [comment] 2015-12-04 16:29
@mjeffe98 was merged into develop ahead of release build, so I think you will be able to test there.

**Comment by mjeffe98** [comment] 2015-12-07 22:50
@sisskind @brianhatchl just want to verify that the expected behavior is that if a layer is not selected i.e. highlighted in yellow, you can't invoke any of the right-click commands.  I didn't think that was the case before.  I do see that right-clicking on a layer doesn't select/de-select it but I also see that you can't pull up the right-click options unless a layer is selected.  After that you can right-click on any layer.

**Comment by mjeffe98** [comment] 2015-12-07 23:08
Here AllDataTypesA is selected but I right-clicked on an unselected layer to export.

![51](https://cloud.githubusercontent.com/assets/7560096/11642707/3c1accb4-9cf4-11e5-9505-9724926ab07a.gif)

**Comment by sisskind** [comment] 2015-12-07 23:10
That was the expected behavior. Do you think it should be different?

**Comment by mjeffe98** [comment] 2015-12-07 23:14
I think based on the logic described in the ticket we should only allow right-click menu options for the selected layer.  Any unselected layers should not allow right-click.

**Comment by sisskind** [comment] 2015-12-08 13:00
Ok - will reopen and adjust.

**Comment by sisskind** [comment] 2015-12-08 13:27
Pushed to develop (https://github.com/ngageoint/hootenanny-ui/pull/72)

**Comment by mjeffe98** [comment] 2015-12-08 20:26
Let me know when this is pushed to release

**Comment by sisskind** [comment] 2015-12-08 20:31
https://github.com/ngageoint/hootenanny-ui/pull/77

**Comment by mjeffe98** [comment] 2015-12-08 21:57
Looks good

**Closed by mjeffe98** 2015-12-08 21:57 UTC
Labels: Status: Ready for Test, Type: Bug
