### ISSUE TITLE
Brazil POI data merging changeset save issue - 5496 branch

### ISSUE THREAD

**Issue by bwitham** [ngageoint/hootenanny-ui#11] opened 2015-11-09 22:12 UTC
Merge the first ~7 reviews after conflating Brazil.  Shown an error message about feature needed for review has been deleted and that you'll be taken to a different review. Also, the zoom levels become NaN's and no map is displayed.

1.  I don't believe this error message should occur, b/c if a feature was deleted, then all of its reviews should have been already resolved.  

2. I was getting this error repeatedly.  In theory, after the first jump to a new review, it should be unlikely this error would be seen again...although this may not be the case in practice..not sure.

3. Of course, the NaN zoom levels shouldn't ever happen.

**Comment by jchoi1267** [comment] 2015-11-10 22:49
This was caused by trying to zoom to empty relation

**Comment by jchoi1267** [comment] 2015-11-10 22:49
Committed

**Closed by jchoi1267** 2015-11-10 22:49 UTC
Labels: bug
