### ISSUE TITLE
"Cannot ready property 'id' of undefined" message shown while review Brazil data - 5496 branch

### ISSUE THREAD

**Issue by bwitham** [ngageoint/hootenanny-ui#12] opened 2015-11-09 22:20 UTC
Having trouble consistently repeating this...occurring occasionally.  After it happens, the zoom levels go to NaN's

**Comment by jchoi1267** [comment] 2015-11-10 03:31
This may be fixed by the zoom level bug fix which I will commit tomorrow...

**Comment by jchoi1267** [comment] 2015-11-10 22:52
This was caused by triangle relation where following was happening (R = relation n=node)
R1 = merged_n1
R2 = merged_n2
R3 = (n1,n2)
 
When we merge R3
R1=nothing
R2=nothing
R3= merged_n3

Fixed by making empty relation auto resolved

**Closed by jchoi1267** 2015-11-10 22:52 UTC
Labels: bug
