### ISSUE TITLE
Right-click menu display issues

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#273] opened 2016-02-29 17:21 UTC
Testing on the latest develop, it looks like there is an issue with GetLayers that @jchoi1267 pointed out but this is showing up in the UI in the following way.  If you refresh ctrl-shift-r on your browser than go to the datasets tab in manage and right-click on a dataset you won't get the menu options but if you right-click on a folder or right-click from the main map on the layer (zoom to layer), the context menu will reappear for all datasets.  There seems to be an issue instantiating the initial right-click menu options for the first time.

**Comment by jchoi1267** [comment] 2016-02-29 17:38
@sisskind This is caused by context.hoot().model.layers.setSelectedLayers(selectedLayerIDs); not setting value since the code before returns before it gets chance.

See hoot/conntrol/utilities/Folder. js line 474. Moving to line 464 seems to fix it..

**Comment by sisskind** [comment] 2016-02-29 21:13
@mjeffe98 Ready for test.

**Comment by mjeffe98** [comment] 2016-03-16 15:58
This issue has resurfaced on the release.  Right-click menu options are not displaying initially in the Datasets tab.  User has to do something to allow them to work such as right click Zoom to Layer.

**Comment by sisskind** [comment] 2016-03-16 16:14
@mjeffe98 was this found on selma or on local?

**Comment by mjeffe98** [comment] 2016-03-16 16:15
selma release

**Comment by mjeffe98** [comment] 2016-03-17 19:02
@sisskind  more of a nuisance than a blocker.  to instantiate the right-click dataset menu options you need to click on a folder first and right click on any dataset to see the context menu.  https://github.com/ngageoint/hootenanny-ui/commit/c39c71c1f4e4d5407418d38df5c2696f4ca63852 should be in the release but for some reason the issue has resurfaced.

**Closed** 2016-03-17 20:21 UTC
Labels: Category: UI, Identified During Regression Test, Priority: High, Type: Bug
