### ISSUE TITLE
Add crop functionality to UI

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#5] opened 2015-11-03 22:00 UTC
Ability to crop dataset(s) to area (visible extent, bounding box, or free-form area).

**Comment by sisskind** [comment] 2015-11-16 22:46
@jchoi1267 Can you review clip branch in hoot-ui (https://github.com/ngageoint/hootenanny-ui/compare/develop...clip) and hoot (https://github.com/ngageoint/hootenanny/compare/develop...clip)?

**Comment by sisskind** [comment] 2015-11-19 16:05
@brianhatchl if you have bandwidth to review, can you take a look?

**Comment by jchoi1267** [comment] 2015-11-19 23:04
@sisskind Merged service code but there was conflict with UI side and could not merge it. Please merge in the UI.

BTW, looks great! Just minor point is it would be great if there was some way to track when clip is done..

**Comment by sisskind** [comment] 2015-11-19 23:52
Will merge in UI. There should be a pop up when clip is complete - will double check that.

**Comment by mjeffe98** [comment] 2015-11-20 17:42
@sisskind.  Looks good!  I noticed that the clips that I've generated don't have bbox drawn on the map like layers that are ingested into Hoot.  Is that by design?  I think it would be useful to have a visual bbox like the parent layer.  Would also be ideal to provide a name and folder location for the output rather than having to rename or move after.

**Comment by mjeffe98** [comment] 2015-11-20 17:44
@jchoi1267 @sisskind the pop-up I assume in this case is the notification message in blue in the corner that the clip job was submitted.  Nothing indicating that it's complete.

**Comment by sisskind** [comment] 2015-11-20 17:49
* Can script up modal window for user to select folder where to drop clip with option to name.

* Unsure what you mean by bounding box -- layers that are clipped should be treated as any other layer, so unsure if this is a clip bug or not.

* What layers are you using to clip?  I'm clipping small area, but get this output:
![image](https://cloud.githubusercontent.com/assets/6191659/11307244/e981d94c-8f84-11e5-8776-49cea6542d9f.png)

**Comment by mjeffe98** [comment] 2015-11-20 18:07
* By bounding box I was referring to the actual bbox drawn around the data. The second iteration it seemed to draw so perhaps this was just a rendering issue on my end.  (a separate side note, occasionally the clip define bbox doesn't always display on screen).   

![image](https://cloud.githubusercontent.com/assets/7560096/11307606/3f944f52-8f6e-11e5-9f54-a5b3ccd299fb.png)

* Not getting the green success notification.

**Comment by mjeffe98** [comment] 2015-11-20 18:15
The UI log just has the job submitted notice but not the created message.
"11/20/2015, 10:01:13 AM: Clip Brazil_SaoPaulo_OsmPois has been submitted."
"11/20/2015, 9:49:30 AM: Clip Brazil_SaoPaulo_OsmPois has been submitted."

**Comment by sisskind** [comment] 2015-11-20 18:26
New tasks:
* Create modal window for user to confirm clip and select name/folder (or accept defaults)
* Ensure proper alert reporting when datasets are submitted and confirmed on completion

**Comment by mjeffe98** [comment] 2015-11-20 18:26
* example of the Clip to Bounding Box not displaying on the map when drawn.

![clip_bbox_notdisplaying](https://cloud.githubusercontent.com/assets/7560096/11308089/1049137e-8f71-11e5-8664-2317af92bfff.gif)

**Comment by mjeffe98** [comment] 2015-11-20 20:07
Just testing zenhub.io file upload [DcGisRoads.osm](https://files.zenhub.io/564f7d747ec9ca497289da1b)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by sisskind** [comment] 2015-11-28 21:12
~~Create modal window for user to confirm clip and select name/folder (or accept defaults)~~
~~Ensure proper alert reporting when datasets are submitted and confirmed on completion~~
~~Ensure bounding box appears as you draw (change to click-drag as opposed to two clicks)~~

Just needs finishing touches (verify layer name is valid, etc.) before being ready for test.

**Comment by sisskind** [comment] 2015-11-30 14:17
@mjeffe98 Committed to develop branch (https://github.com/ngageoint/hootenanny-ui/commit/2412fa974b26f872106c425e5e7e293e0195cf3e) and ready for further testing.

**Comment by mjeffe98** [comment] 2015-12-01 19:36
not seeing the Success message on selma but clip is working as designed with the new UI dialog

**Closed by mjeffe98** 2015-12-01 19:36 UTC
Labels: Status: Ready for Test, Type: Feature
