### ISSUE TITLE
Conflating a dataset two or more times in a row results in no reviews the the 2nd and subsequent runs

### ISSUE THREAD

**Issue by bwitham** [ngageoint/hootenanny-ui#71] opened 2015-12-07 19:14 UTC
* conflate AllDataTypesA/B
* get expected number of reviews
* resolve all reviews
* click the trash can for the output layer; confirm dialog
* conflate AllDataTypesA/B
* receive the message that there are no more features to review, when there should be some to review

The only way I can break this cycle is by refreshing the browser.

This is possibly related to #64

**Comment by bwitham** [comment] 2015-12-07 19:15
@mjeffe98 @jchoi1267 @brianhatchl @sisskind

**Comment by brianhatchl** [comment] 2015-12-07 21:02
I see this happens whenever a review mode has been done previously.  That is, you can simply 
* load a dataset with open reviews.
* remove it from the map.
* attempt to load another dataset with open reviews.
* get the Failed to retrieve next feature for review! error #64

**Comment by brianhatchl** [comment] 2015-12-07 21:10
This is the error 
```
TypeError: Cannot read property 'key' of undefined at Conflict.startReview.getRelationFeature (http://localhost:8080/js/hoot/control/Conflicts.js:348:46) at http://localhost:8080/js/hoot/control/Conflicts.js:403:29 at http://localhost:8080/js/hoot/model/rest.js:745:17 at Object.<anonymous> (http://localhost:8080/js/lib/d3.min.js:1:10988) at Object.t (http://localhost:8080/js/lib/d3.min.js:1:1368) at XMLHttpRequest.u (http://localhost:8080/js/lib/d3.min.js:1:9850)
```
happening on https://github.com/ngageoint/hootenanny-ui/blob/release/js/hoot/control/Conflicts.js#L348

**Comment by mjeffe98** [comment] 2015-12-07 21:12
I can reproduce this consistently when loading a dataset after removing a previous one with open reviews.

**Comment by jchoi1267** [comment] 2015-12-07 22:46
Committed the change to release branch.
This was caused by class variable not being cleaned up when review gets removed.

**Closed** 2015-12-08 17:31 UTC
Labels: Status: Accepted/Closed, Type: Bug
