### ISSUE TITLE
Getting reviews with single features when conflating POIs

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#158] opened 2016-01-08 22:14 UTC
When conflating a Sao Paulo subset of the Brazil (geonames, OSM) data I observed a number of single feature reviews where only one feature was shown in the review table. In some cases the highlight color of the map POI does not match the review table, in other cases it does.  Typically clicking resolve proceeds to the next review but if you happen to click merge (even though there is nothing to merge) a longer delay occurs.  

Some ex: 
Geonames: Comfort Hotel Downtown; L'Hotel; Gran Corona 
OSM: Bela Vista; Largo Treze

![single poi](https://cloud.githubusercontent.com/assets/7560096/12210874/072b3cf0-b612-11e5-8e15-90c5e139e2f2.png)

**Comment by mjeffe98** [comment] 2016-01-08 22:52
Observing multiple reviews in the dc poi dataset (dcpoi/mapcruzen) with single POIs.

ex: COLUMBIA HEIGHTS COMMUNITY CENTER; MERIDIAN HOUSE, etc.

**Comment by mjeffe98** [comment] 2016-01-08 22:58
I think given the fact that this didn't occur in prior versions makes me believe we have introduce a new UI behavior during review.

**Comment by jchoi1267** [comment] 2016-01-11 21:13
The failure was happening at where we load review relation members. We assumed that if context.hasEntity returns for a relation then all the members are also loaded but it turns out it was not true. Implemented so it checks loaded count vs members count and if not match load the relation.

**Comment by jchoi1267** [comment] 2016-01-11 21:14
Committed to release branch only.

**Comment by mjeffe98** [comment] 2016-01-11 23:19
No longer getting this with the DC POI data but I did see it again with the SaoPaulo data e.g. Comfort Hotel Dowtown in geonames showing up a single red column but only 1 blue highlighted POI appears on the map.  It appears the color coding is getting crossed up (blue POI marker representing the geonames data on the map and a red table representing the geonames feature in the review).  @brianhatchl any ideas for the color mixup?

**Comment by mjeffe98** [comment] 2016-01-11 23:20
Another example, Gran Corona.  I did rebuild the release branch as well so I think it has the commit.

![image](https://cloud.githubusercontent.com/assets/7560096/12249777/c746ae50-b876-11e5-867f-64707b8f33e7.png)

**Comment by brianhatchl** [comment] 2016-01-11 23:37
Yes, if in the review item, the review feature and review against feature are the same, the svg feature will get tagged with both `activeReviewFeature` and `activeReviewFeature2` css class names and the last one listed will effectively set the halo color.
https://github.com/ngageoint/hootenanny-ui/blob/develop/js/hoot/control/conflicts/map/FeatureHighlighter.js#L62-L83
One way to check is to examine the highlighted feature in the dev console and see if it has both these classes listed.

**Comment by mjeffe98** [comment] 2016-01-11 23:59
@brianhatchl thanks for the explanation.  @jchoi1267 with your commit should we still be seeing single feature reviews?

**Comment by jchoi1267** [comment] 2016-01-12 16:21
hmm.. 
Single point should be rare occurrence...
Need to revisit with SaoPaulo data

**Comment by jchoi1267** [comment] 2016-01-12 16:50
@mjeffe98 Did couple of hundreds of clicking next using Merged_Brazil_saopaulo on selma and still can not reproduce..

Let me know after doing browser refresh you still get the problem..

Thanks

**Closed** 2016-01-12 17:31 UTC
Labels: Category: UI, Identified During Regression Test, Priority: Medium, Status: In Progress
