### ISSUE TITLE
Resolving reviews in Congo OSM/MGCP line data triggers error: Cannot read property 'members' of undefined

### ISSUE THREAD

**Issue by mikejeffe** [ngageoint/hootenanny-ui#314] opened 2016-03-14 16:54 UTC
Consistently hitting this issue when conflating OSM and MGCP roads and bridges data.  When you click the resolved button or the hot key to resolve the conflict, a red message pops up in the corner saying "Cannot read property 'members' of undefined..."  The dev console shows a similar error as well as entity 'x' not found.  

ReviewResolution.js:144 TypeError: Cannot read property 'members' of undefined(…)_handleError @ ReviewResolution.js:144
locale.js:32 Missing en translation: review.sharereview.descriptiont @ locale.js:32

To reproduce:
1) ingest data attached to https://github.com/DigitalGlobe/dgis-devops/issues/76
* https://github.com/DigitalGlobe/dgis-devops/files/171926/Congo_MGCP_Roads_Bridges.zip
* https://github.com/DigitalGlobe/dgis-devops/files/171930/Congo_OSM_Roads_Bridges.zip

2) Conflate reference layer = mgcp; secondary = osm
3) Step through reviews until you get the pop-up error.

**Comment by mjeffe98** [comment] 2016-03-14 16:54
@sisskind not sure who to assign this to.

**Comment by sisskind** [comment] 2016-08-05 12:47
@briandaviddavidson @jcp2236 @rmrice can you all try to recreate?

**Comment by jcp2236** [comment] 2016-08-08 17:40
I haven't been able to reproduce this error, anyone else want to give it a shot?

**Comment by briandaviddavidson** [comment] 2016-08-08 17:57
Once I rebuild vagrant, I will try

**Comment by briandaviddavidson** [comment] 2016-08-10 12:56
Unable to reproduce the error as well. @rmrice can you give it a whirl before you go on PTO?

**Comment by rmrice** [comment] 2016-08-10 15:33
I've gotten a few errors

1. The one for this ticket. I think it popped up after I tried to save an edit after recreating a line.
![screenshot from 2016-08-10 11 31 26](https://cloud.githubusercontent.com/assets/17434033/17559951/26e0a258-5eee-11e6-8ab8-807191a7da86.png)

2. "Review get refs failed. failed to retrieve review refs. Error: [object XMLHttpRequest]" when hitting "Resolve."
![screenshot from 2016-08-10 11 04 37](https://cloud.githubusercontent.com/assets/17434033/17559566/ac040fe4-5eec-11e6-9840-4890c4110a40.png)

Also, I was running into an issue where I swapped from conflated layer to input layer, and got stuck because hoot won't let you go to the next review unless you are in the conflated mode. I wasn't able to switch to conflated mode because I couldn't get the radial menu to show up, the hot key didn't work, and checking/unchecking the data layers from the side panel didn't work. This seemed to be hit or miss but It happened a few times and I think also to @jcp2236. This probably needs to be it's own ticket.

**Comment by jcp2236** [comment] 2016-08-10 15:44
I can confirm I've run into the third issue listed where you can no longer progress through the review items by clicking 'previous', 'next', or 'resolved'. That was the only error I was able to generate in testing.

**Comment by sisskind** [comment] 2016-08-22 14:48
So...another fun error, happening with larger review features. FYI @bwitham @brianhatchl 

This will cycle for minutes:
![image](https://cloud.githubusercontent.com/assets/6191659/17858892/86c7f6ba-6855-11e6-8fdd-accf9de51d52.png)

Then this:
![image](https://cloud.githubusercontent.com/assets/6191659/17858970/c88fb09c-6855-11e6-983c-c013570128fc.png)

with console error: ```osmauth.js:2148 POST http://localhost:8888/hoot-services/osm/api/0.6/changeset/250/upload?mapId=196 500 (Internal Server Error)```

Believe it is possible that the 'Updating changes to Hootenanny' is causing a delay that causes Hoot to lose focus on feature trying to save.  Going to follow that thread unless other cause immediately comes to mind.

**Comment by bwitham** [comment] 2016-08-22 16:30
I'm seeing a server out of memory error.  If this is consistently reproducible, would see if Dmitriy can diagnose.

**Closed** 2016-09-13 17:06 UTC
Labels: Category: UI, Priority: Medium, Status: In Progress, Type: Bug
