### ISSUE TITLE
Zoom level does not change when reviews are loaded.

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#66] opened 2015-12-04 21:16 UTC
Conflating DC POI datasets, I've noticed that in addition to the first review pair not highlighting, the map does not zoom in on the review features but remains at the scale of the layer bbox.  As you step through each successive review pair, you remain at the same map scale.  I think we used to zoom down to the point where the review pair distance defined the visible map extent.  Also if you zoom manually, subsequent reviews will stay at that zoom level.

**Comment by sisskind** [comment] 2015-12-07 19:52
This is occurring by design, from a previous requirement:
https://github.com/ngageoint/hootenanny-ui/blob/develop/js/hoot/control/Conflicts.js#L128
```
var zoom = Math.min(20, map.zoom());
                if (zoom < 16) {
                    zoom = 16.01;
                }
                map.centerZoom(entityCenter,(zoom));
```
Therefore, if your zoom level is between 16-20, it will not change.  This may only be noticed now (https://github.com/ngageoint/hootenanny-ui/issues/62#issuecomment-162634409)

**Comment by sisskind** [comment] 2015-12-08 16:07
This was a requirement to avoid zooming past level 16 (which would turn on density raster).  Since density raster has been replaced, this is no longer necessary and will be reversed.

**Comment by sisskind** [comment] 2015-12-08 16:14
@mjeffe98 Ready for test (https://github.com/ngageoint/hootenanny-ui/pull/74)

**Comment by mjeffe98** [comment] 2015-12-08 17:51
Not entirely sure that I am seeing the finished product on develop.  Let's regroup after.

**Comment by mjeffe98** [comment] 2015-12-08 22:10
I don't see the zoom level changing after adding a layer containing reviews.

**Comment by sisskind** [comment] 2015-12-08 22:21
Issue not fully resolved -- moving to 16-December sprint.

**Comment by sisskind** [comment] 2015-12-09 16:45
Merged into develop.

**Comment by sisskind** [comment] 2015-12-09 16:52
https://github.com/ngageoint/hootenanny-ui/pull/80

**Closed** 2015-12-09 17:31 UTC
Labels: Priority: Medium, Status: Accepted/Closed, Type: Bug
