### ISSUE TITLE
"Batman Mode"

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#137] opened 2016-01-04 14:11 UTC
Hootenanny will randomly go into Batman Mode...where coordinates are NaN NaN NaN NaN (get it?  Sing the Batman theme in your head...)

Screen goes black, appears hyper-zoomed in, and obviously coordinates are not a number.

**Comment by mjeffe98** [comment] 2016-01-06 18:55
Occurs mainly in review mode and possibly linked to certain reviews running on 0.2.19.  Retest with current version.

**Comment by mjeffe98** [comment] 2016-01-06 19:23
Will investigate to reproduce.

**Comment by mjeffe98** [comment] 2016-01-11 23:15
Recreated this with the PortAuPrince_osm/mgcp datasets (uncropped).  There are around 415 reviews in this data but I observed "Batman" mode when I clicked on a review against a relationand the coords switched to NaN NaN etc... and the map went black (URL coords also displayed as NaN,NaN etc..

**Comment by mjeffe98** [comment] 2016-01-11 23:24
example of what happens to the URL:  http://localhost:8080/hootenanny-id/#background=Bing&id=r111_550&map=NaN/NaN/NaN&overlays=,550

![image](https://cloud.githubusercontent.com/assets/7560096/12249843/58520750-b877-11e5-82bf-6dbb2ccdd14c.png)

**Comment by mjeffe98** [comment] 2016-01-12 19:36
@sisskind @jchoi1267 do we have enough information to assign to a developer?

**Comment by jchoi1267** [comment] 2016-01-13 20:32
Updated the setProcessing masking. Although there is sometimes 0.5 sec gaps between locking it should cover most of processing range. Could not create lock covers whole process since tile loading is extremely asychronous operation and can not cover all entry and exit points

**Comment by mjeffe98** [comment] 2016-01-14 19:46
Resolved > 100 reviews without getting the NaN issue to resurface.

**Closed by mjeffe98** 2016-01-14 19:46 UTC
Labels: Category: UI, Priority: High, Status: New/Undefined, Status: Ready for Test, Type: Bug
