### ISSUE TITLE
Deleting line/area feature in relation leaves nodes

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#144] opened 2016-01-04 14:20 UTC
When you delete a line or area feature that is involved in a relation, it creates point features at each node that then need to be deleted as well.

**Comment by mjeffe98** [comment] 2016-01-06 19:22
Will investigate datasets to reproduce behavior.

**Comment by mjeffe98** [comment] 2016-01-11 17:28
@sisskind I cannot reproduce this error with any of the datasets that I have containing line or area features that are part of a relation.  In both cases I have deleted the feature containing the relation and no additional nodes have been added. Please supply the dataset where this has been reported.

**Comment by sisskind** [comment] 2016-01-11 17:55
![issue144](https://cloud.githubusercontent.com/assets/6191659/12241692/8f62dc16-b862-11e5-82eb-1d2aed0db211.gif)

**Comment by mjeffe98** [comment] 2016-01-11 19:49
@jchoi1267 @sisskind 
I was not able to recreate the exact same review scenario as one above in @sisskind comment but I was able to recreate with a different feature using a subset of the original source data (attached PortAuPrince_clipped.zip).  Road feature in conflated layer (Entree Desermithe) which is b/w the small town of Juvenot and the larger town Petionville shown here appears to be a way containing nodes that are part of a relation. The same road feature in the input datasets do not contain the same feature geometry and relation so this appears to be introduced during the merge. 

![image](https://cloud.githubusercontent.com/assets/7560096/12244382/4a1c3dd2-b858-11e5-8120-dffddcbf0278.png)

When you delete the feature in the merged output, there are remaining nodes as described in the ticket but these remaining nodes were in fact added during the conflation process and not part of the original input data sources.  Doesn't seem like a bug since these nodes are part of the relation and not part of the linear feature being deleted.

![relation_delete](https://cloud.githubusercontent.com/assets/7560096/12244585/49c9db54-b859-11e5-87fb-5ab683115102.gif)




 [PortAuPrince_clipped.zip](https://files.zenhub.io/56940480547e1dfa3ce919b4)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by mjeffe98** [comment] 2016-01-11 20:07
This is just the screen grab of the POI markers that are generated in the conflated output for  the Entree Desermithe linear road feature.  Looking closely, it appears that they don't necessarily line up with the merged output feature but perhaps originate from either of the input layers.

![image](https://cloud.githubusercontent.com/assets/7560096/12245037/4f16c2f0-b85b-11e5-822b-865e1cca229b.png)

**Comment by mjeffe98** [comment] 2016-01-12 18:46
DcGis vs DcTiger provides another good example that is easily reproduce-able. The last reviewed feature is WEST BASIN DR SW.  If you delete the merged (green) features, nodes remain but when you delete the original input data, no nodes appear.  

![deleting_line_poi](https://cloud.githubusercontent.com/assets/7560096/12273253/a5d7704e-b919-11e5-9311-4348d19cb2e9.gif)

**Comment by mjeffe98** [comment] 2016-01-14 17:20
@jchoi1267 can you take a look now that the issue is well documented?

**Comment by jchoi1267** [comment] 2016-01-14 17:21
@mjeffe98 got it

**Comment by mjeffe98** [comment] 2016-01-14 18:24
Other detail added is that the behavior changes depending on the zoom level.  When zoomed way out on certain datasets the nodes appear as separate features (circle with black dots) but when zoomed in, the nodes are no longer visible.  Must be related to loading the feature containing relations at different zoom levels.

**Comment by jchoi1267** [comment] 2016-01-14 21:05
This bug was caused by not passing in layerName correctly during loadMissing..

**Comment by mjeffe98** [comment] 2016-01-14 21:09
let me know when its merged and reviewed

**Comment by jchoi1267** [comment] 2016-01-15 15:09
Should be in develop branch

**Comment by mjeffe98** [comment] 2016-01-18 21:12
I think this is great! Change is there and I no longer see the nodes left behind with the merged features.

**Closed by mjeffe98** 2016-01-18 21:12 UTC
Labels: Category: UI, Priority: High, Status: Ready for Test, Type: Bug
