### ISSUE TITLE
Hoot switches off conflated layers without notifying the user, then user can't turn it back on

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#816] opened 2017-01-04 16:58 UTC
While going through the reviews, Without input from the user, Hootenanny deactivated/unchecked the conflated layer and activated/checked the two input layers. Then, if they user unchecks the two input layers, and checks the conflated layer, the conflated layer won't render. I would expect that only the user could switch on/off the different layers. I'd also expect that toggling the conflated layer would result in that layer rendinging in hoot. Tried different zoom levels. I had this yesterday but didn't have time to fully investigate. A colleague had this today.

**Comment by sisskind** [comment] 2017-01-04 16:58
https://github.com/DigitalGlobe/VGI-team-repo/issues/427

**Comment by brianhatchl** [comment] 2017-01-10 22:23
I've reproduced this and there seems to be a bug when toggling conflated and source layers with a combination the toggle layers tool available on the feature radial menu:
![screenshot from 2017-01-10 17 17 25](https://cloud.githubusercontent.com/assets/2600932/21827267/ec6d752c-d758-11e6-9e92-c4b8a94f6cda.png)

and the use of the layer list in the background settings:
![screenshot from 2017-01-10 17 17 45](https://cloud.githubusercontent.com/assets/2600932/21827264/e90359d8-d758-11e6-815e-19327615e4b6.png)

It seems I can't control the visibility of the merged layer with its layer list entry (only with the toggle tool), but I can with the source layers entries.

One solution could be to make the layer list checkboxes readonly, and only reflect the state of the layer visibility but not control it.  Or we figure out why the layer list entry for the merged layer is not working.

**Comment by sisskind** [comment] 2017-01-11 12:21
@briandaviddavidson do you think this is a side effect of removing the duplicate names in the sidebar?

**Comment by briandaviddavidson** [comment] 2017-01-11 12:51
Maybe. If my memory serves, I think the other duplicate names are just classed with hidden since removing them didn't allow for the toggle to work at all; The hidden ones might be getting toggled somehow. I can take a look at it with @jcp2236.

**Comment by brianhatchl** [comment] 2017-01-11 13:55
Sorry, I should clarify that I reproduced the inability to turn the merge layer off or on from the background settings.  I believe this issue to be solved by the commit above.  I did not reproduce or diagnose what might have caused the merged layer to get swapped with the source layers without user input.

**Comment by jcp2236** [comment] 2017-01-11 14:21
Thanks for clarifying, I'm working on reproducing the merged layer swapping with the source layers. Any suggestions on getting the layer swap issue to occur on my machine @sisskind?

**Comment by brianhatchl** [comment] 2017-01-11 14:27
I thought maybe it was an inadvertent Shift+T but that advertised shortcut seems to be broken.

**Comment by jcp2236** [comment] 2017-01-11 14:39
Yeah, Shift+T seems broken on my end too. I've been hitting the toggles in the background menu and in the radial menu to try to recreate the issue, but the conflated layer is rendering no problem so far.

**Comment by brianhatchl** [comment] 2017-01-11 14:42
The bug only happens when a fresh merged layer is loaded immediately after conflation.  Adding an existing merged layer with reviews doesn't have this problem.

**Comment by jcp2236** [comment] 2017-01-11 14:45
Thanks for the tip, that may explain it

**Comment by brianhatchl** [comment] 2017-04-05 14:04
@jcp2236 is this ready for test?
@kweint can you give it a try?

**Comment by jcp2236** [comment] 2017-04-05 14:31
If @kweint can reproduce the error, we can take a look at it together, but I haven't been able to reproduce the layer swapping even with a freshly conflated layer on my end. I can take a look at it again, but I seem to be able to cycle through reviews with just the expected functionality.

**Comment by jcp2236** [comment] 2017-04-19 18:03
I'd say this is ready to test, seems to be working as intended now. Want to test, @kweint?

**Comment by kweint** [comment] 2017-04-19 18:29
I after testing on a few data sets, I haven't been able to replicate the error. Concurring with @jcp2236 wherein it seems to be working as intended now.

**Closed** 2017-04-19 18:30 UTC
Labels: Category: UI, in progress, Status: In Progress, Type: Bug
